In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [4]:
l = [1,2,3,4,5]

In [5]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

1

In [9]:
arr.shape

(5,)

In [11]:
# if any one item in the list is a string, then all the items of the list will be typecasted to string when list is converted into numpy array
l = [1,2,3,4,"Rishi"]
arr1 = np.array(l)
arr1

array(['1', '2', '3', '4', 'Rishi'], dtype='<U21')

In [13]:
type(l)

list

In [14]:
type(arr1)

numpy.ndarray

In [15]:
arr2 = np.array([[1,2,3], [4,5,6]])

In [16]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 3)

In [23]:
arr3 = np.matrix(arr2)
arr3

matrix([[1, 2, 3],
        [4, 5, 6]])

In [22]:
np.matrix([[1,2], [3,4], [5,6]])

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [24]:
np.asarray([[1,4], [6,7], [9,0]])

array([[1, 4],
       [6, 7],
       [9, 0]])

In [25]:
np.asanyarray(arr2)

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
t = ((1,2,3), (4,5,6))
type(t)

tuple

In [27]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a=5
np.array(5)

array(5)

#Shallow Copy vs Deep Copy

##Shallow Copy
Shallow copy is an imperfect approach to copy. In this, no new array is created but instead when we try to copy one array into another, the new array refers to the same memory location as the original array.
for eg:

```
arr1 is at 310 location.
we did arr2=arr1
now arr2 also points at 310 location
```



Both arr1 and arr2 point at the same memory location.

In [31]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [32]:
arr2 = arr1

In [33]:
arr2

array([1, 2, 3, 4, 5])

In [34]:
arr1[0] = 1000
arr1

array([1000,    2,    3,    4,    5])

In [35]:
arr2

array([1000,    2,    3,    4,    5])

##Deep Copy

Deep copy means the newly created array is perfectly copied without any loose ends. It has no link to the previos/parent array. It is independent. An entirely new array is created with new memory location when .copy() function is used, therefore changes made to the parent array doesn't reflect in the child/copied array.

In [36]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [37]:
arr2 = arr1.copy()
arr2

array([1, 2, 3, 4, 5])

In [38]:
arr1[0] = 1000
arr1

array([1000,    2,    3,    4,    5])

In [39]:
arr2

array([1, 2, 3, 4, 5])

#Multiple ways of generating arrays

In [40]:
np.fromfunction(lambda i,j : i==j, shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [42]:
arr3

matrix([[1, 2, 3],
        [4, 5, 6]])

In [43]:
arr3.size

6

In [44]:
np.fromfunction(lambda i,j : i*j, shape=(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [45]:
np.fromfunction(lambda i,j : i+j, shape=(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [46]:
iterable = (i*i for i in range(5))

In [54]:
np.fromiter(iterable, float)

array([], dtype=float64)

In [55]:
np.fromstring('23 45 67', sep=' ')

array([23., 45., 67.])

In [56]:
np.fromstring('23,45,67', sep=',')

array([23., 45., 67.])

In [60]:
np.arange(1,50,.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5,
       34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. ,
       39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5,
       45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5])

In [61]:
np.linspace(20,60,30)

array([20.        , 21.37931034, 22.75862069, 24.13793103, 25.51724138,
       26.89655172, 28.27586207, 29.65517241, 31.03448276, 32.4137931 ,
       33.79310345, 35.17241379, 36.55172414, 37.93103448, 39.31034483,
       40.68965517, 42.06896552, 43.44827586, 44.82758621, 46.20689655,
       47.5862069 , 48.96551724, 50.34482759, 51.72413793, 53.10344828,
       54.48275862, 55.86206897, 57.24137931, 58.62068966, 60.        ])

linspace gives me 30 equidistant values between 20 and 60

In [63]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [64]:
np.logspace(1,5,10, base=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

##Note
in logspace, values are not equidistant

In [65]:
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [66]:
arr1.shape

(5,)

In [68]:
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
arr3 = np.zeros((2,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [70]:
arr2.shape

(3, 4)

In [71]:
arr3.shape

(2, 3, 4)

In [73]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [75]:
arr * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])