In [ ]:
import numpy as np

In [ ]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
np.empty((3,4), int)
# gives random value

array([[4616189618054758400, 4616189618054758400, 4616189618054758400,
        4616189618054758400],
       [4616189618054758400, 4616189618054758400, 4616189618054758400,
        4616189618054758400],
       [4616189618054758400, 4616189618054758400, 4616189618054758400,
        4616189618054758400]])

In [ ]:
np.eye(5, dtype = int)
#gives identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
import pandas as pd

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
pd.DataFrame(arr)
#converting array into dataframe

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

###Python Random

In [ ]:
import random

In [ ]:
random.choice((1,2,3,4,5,6))

4

In [ ]:
random.choice('vatsalya')

's'

In [ ]:
random.randrange(1,100)

99

In [ ]:
random.random()
#any random number b/w [0,1)

0.20357228035104757

In [ ]:
l = [1,2,3,4,5]
random.shuffle(l)
l

[5, 1, 2, 4, 3]

In [ ]:
random.uniform(7,14)
#uniform distribution of numbers -> STATISTICS

13.58514943633455

###Numpy Random

In [ ]:
np.random.rand(2,3)

array([[0.67951069, 0.64283119, 0.7605724 ],
       [0.89441987, 0.28316551, 0.46832547]])

In [ ]:
np.random.rand(1)

array([0.95923453])

In [ ]:
np.random.rand(5)

array([0.758054  , 0.45252353, 0.53284214, 0.95563628, 0.63721091])

In [ ]:
np.random.randn(2,3)
#normal distribution

array([[-1.48438706,  0.3234065 ,  0.33451804],
       [-0.58644803, -1.28541407, -0.65867463]])

In [ ]:
np.random.random_sample()
#Return random floats in the half-open interval [0.0, 1.0).

0.6360006047277319

In [ ]:
arr = np.random.randint(1,5, size = (3, 4))
arr

array([[2, 3, 4, 2],
       [3, 3, 3, 4],
       [4, 3, 3, 2]])

In [ ]:
arr.size

12

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr

array([[2, 3, 4, 2],
       [3, 3, 3, 4],
       [4, 3, 3, 2]])

In [ ]:
arr.reshape(2, 6)

array([[2, 3, 4, 2, 3, 3],
       [3, 4, 4, 3, 3, 2]])

In [ ]:
#size must be same if you reshape an array
#array size can not change

In [ ]:
arr.reshape(1, 12)

array([[2, 3, 4, 2, 3, 3, 3, 4, 4, 3, 3, 2]])

In [ ]:
arr.reshape(6, 2)

array([[2, 3],
       [4, 2],
       [3, 3],
       [3, 4],
       [4, 3],
       [3, 2]])

In [ ]:
arr.reshape(12, )
#convert to 1D

array([2, 3, 4, 2, 3, 3, 3, 4, 4, 3, 3, 2])

In [ ]:
#sometimes ML model requires a specific shape to work

In [ ]:
arr

array([[2, 3, 4, 2],
       [3, 3, 3, 4],
       [4, 3, 3, 2]])

In [ ]:
arr.reshape(4, -1)

array([[2, 3, 4],
       [2, 3, 3],
       [3, 4, 4],
       [3, 3, 2]])

In [ ]:
arr.reshape(4, -1000)

array([[2, 3, 4],
       [2, 3, 3],
       [3, 4, 4],
       [3, 3, 2]])

In [ ]:
arr.reshape(3, -1)

array([[2, 3, 4, 2],
       [3, 3, 3, 4],
       [4, 3, 3, 2]])

In [ ]:
arr.reshape(-1, 6)

array([[2, 3, 4, 2, 3, 3],
       [3, 4, 4, 3, 3, 2]])

In [ ]:
arr.reshape(-1, -1)

ValueError: can only specify one unknown dimension

In [ ]:
arr.reshape(-1, 4)

array([[2, 3, 4, 2],
       [3, 3, 3, 4],
       [4, 3, 3, 2]])

In [ ]:
arr.reshape(12, 1).base

array([[2, 3, 4, 2],
       [3, 3, 3, 4],
       [4, 3, 3, 2]])

In [ ]:
arr.reshape(12, 1)

array([[2],
       [3],
       [4],
       [2],
       [3],
       [3],
       [3],
       [4],
       [4],
       [3],
       [3],
       [2]])

In [ ]:
#reshape does shallow copy

In [ ]:
arr

array([[2, 3, 4, 2],
       [3, 3, 3, 4],
       [4, 3, 3, 2]])

In [ ]:
arr.reshape(2, 2, 3)

array([[[2, 3, 4],
        [2, 3, 3]],

       [[3, 4, 4],
        [3, 3, 2]]])

In [ ]:
arr.reshape(4, 3, 1)

array([[[2],
        [3],
        [4]],

       [[2],
        [3],
        [3]],

       [[3],
        [4],
        [4]],

       [[3],
        [3],
        [2]]])

In [ ]:
l = [1,2,3,4]
arr = np.array(l)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
arr2 = np.array([[2,3], [4,5]])

In [ ]:
arr2

array([[2, 3],
       [4, 5]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2.ndim

2

In [ ]:
arr3 = np.zeros((1,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr3.ndim

3

In [ ]:
arr4 = np.zeros((1,1,3,4))
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
arr4.shape

(1, 1, 3, 4)

In [ ]:
arr4.ndim

4

In [ ]:
arr3 = np.zeros((3,3,4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr3.shape

(3, 3, 4)

In [ ]:
arr1 = np.random.randint(1,10,(5,6))
arr1

array([[2, 8, 2, 1, 1, 2],
       [8, 6, 3, 7, 9, 2],
       [4, 6, 2, 4, 5, 9],
       [9, 9, 4, 1, 4, 3],
       [8, 7, 1, 8, 7, 7]])

In [ ]:
arr1 > 5

array([[False,  True, False, False, False, False],
       [ True,  True, False,  True,  True, False],
       [False,  True, False, False, False,  True],
       [ True,  True, False, False, False, False],
       [ True,  True, False,  True,  True,  True]])

In [ ]:
arr1[arr1 > 5]
#give me all the values in the array where this condition is true

array([8, 8, 6, 7, 9, 6, 9, 9, 9, 8, 7, 8, 7, 7])

In [ ]:
arr1[arr1 < 4]

array([2, 2, 1, 1, 2, 3, 2, 2, 1, 3, 1])

In [ ]:
arr1[arr1 == 6]

array([6, 6])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr[0]

1

In [ ]:
arr1 = arr1[arr1 > 5]
arr1

array([8, 8, 6, 7, 9, 6, 9, 9, 9, 8, 7, 8, 7, 7])

In [ ]:
arr1.shape

(14,)

##Slicing

In [ ]:
arr1 = np.random.randint(1,10,(5,6))
arr1

array([[5, 3, 8, 3, 4, 6],
       [3, 4, 4, 4, 4, 1],
       [6, 1, 5, 2, 8, 4],
       [7, 7, 4, 7, 5, 4],
       [5, 4, 1, 3, 4, 1]])

In [ ]:
arr1[2][4]

8

In [ ]:
arr1[2:4]

array([[6, 1, 5, 2, 8, 4],
       [7, 7, 4, 7, 5, 4]])

In [ ]:
arr1[[2,4]]

array([[6, 1, 5, 2, 8, 4],
       [5, 4, 1, 3, 4, 1]])

In [ ]:
arr1[0, 1:4]

array([3, 8, 3])

In [ ]:
arr1[1:3, 2:5]

array([[4, 4, 4],
       [5, 2, 8]])

In [ ]:
arr1[2: , 1:3+1]

array([[1, 5, 2],
       [7, 4, 7],
       [4, 1, 3]])

In [ ]:
arr1[3: , 4: ]

array([[5, 4],
       [4, 1]])

In [ ]:
arr1[[2,4], [0,2]]

array([6, 1])

##Operations on Matrix

In [ ]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [ ]:
arr1

array([[2, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [ ]:
arr2

array([[1, 2, 2],
       [1, 2, 1],
       [2, 2, 2]])

In [ ]:
arr1 + arr2

array([[3, 4, 3],
       [2, 4, 2],
       [3, 4, 3]])

In [ ]:
arr1 - arr2

array([[ 1,  0, -1],
       [ 0,  0,  0],
       [-1,  0, -1]])

In [ ]:
arr1 * arr2

array([[2, 4, 2],
       [1, 4, 1],
       [2, 4, 2]])

In [ ]:
arr1 / arr2

array([[2. , 1. , 0.5],
       [1. , 1. , 1. ],
       [0.5, 1. , 0.5]])

##Matrix Multiplication / Dot Product

In [ ]:
arr1 @ arr2
#python way of matrix multiplication

array([[ 6, 10,  8],
       [ 5,  8,  6],
       [ 5,  8,  6]])

In [ ]:
arr1 / 0

<ipython-input-133-f39b50d43667>:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#numpy understands infinity, while python doesn't

##Broadcasting

In [ ]:
arr = np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
a + arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
a = np.array([1,2,3])
#1D

In [ ]:
a = np.array([[1,2,3]])
#2D

In [ ]:
a.T

array([[1],
       [2],
       [3]])

In [ ]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [ ]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [ ]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.     ],
       [0.     , 0.30103, 0.     ],
       [0.     , 0.30103, 0.     ]])

In [ ]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])

In [ ]:
a

array([[1, 2, 3]])

In [ ]:
np.min(a)

1

In [ ]:
np.max(a)

3

In [ ]:
np.min(arr1)

1

In [ ]:
np.max(arr1)

2

In [ ]:
arr1

array([[2, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [ ]:
arr1.T

array([[2, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

In [ ]:
arr1.flatten()

array([2, 2, 1, 1, 2, 1, 1, 2, 1])

In [ ]:
#expand_dims -> expands the array by inserting a new axis
np.expand_dims()

Expand the shape of an array.

Insert a new axis that will appear at the axis position in the expanded
array shape.

axis = 1 -> column-wise

axis = 0 -> row-wise

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(arr)

45

In [ ]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [ ]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[1, 2, 3, 4]])

In [ ]:
#every time one dimension will be increased

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
arr = np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.expand_dims(arr, axis = 0)
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr = np.expand_dims(arr, axis = 1)
arr

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])