In [1]:
import numpy as np
data = np.array([[1],[2],[3]])

In [2]:
data.ndim

2

In [3]:
data

array([[1],
       [2],
       [3]])

Reduces the dimension by 1

In [4]:
squeezed_data = np.squeeze(data)
squeezed_data

array([1, 2, 3])

In [5]:
squeezed_data.ndim

1

In [6]:
#repeat
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [7]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [8]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [9]:
#repeat always gives the result after flattening the array

In [13]:
#repeat columns
np.repeat(a, 4, axis=1)

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [3, 3, 3, 3, 4, 4, 4, 4]])

In [14]:
#repeat rows
np.repeat(a, 4, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])

In [23]:
#roll -> roll array elements along a given axis
#not very widely used....  A similar method is used extensively though in PANDAS called, 'shift'...in time-series data

In [16]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.roll(data, 1)

array([[3],
       [1],
       [2]])

In [20]:
np.roll(data, -1)

array([[2],
       [3],
       [1]])

In [21]:
#diagonal

In [22]:
d = np.array([1,2,3,4])
np.diag(d)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
a = np.array([[[1,2,3],[4,5,6]], [[11,22,33],[44,55,66]], [[111,222,333],[444,555,666]]])
a

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 11,  22,  33],
        [ 44,  55,  66]],

       [[111, 222, 333],
        [444, 555, 666]]])

In [26]:
np.roll(a, 1, axis=0)

array([[[111, 222, 333],
        [444, 555, 666]],

       [[  1,   2,   3],
        [  4,   5,   6]],

       [[ 11,  22,  33],
        [ 44,  55,  66]]])

In [27]:
np.roll(a, 1, axis=1)

array([[[  4,   5,   6],
        [  1,   2,   3]],

       [[ 44,  55,  66],
        [ 11,  22,  33]],

       [[444, 555, 666],
        [111, 222, 333]]])

#Binary Operation on Array

In [28]:
arr1 = np.random.randint(1, 10, (3,4))
arr2 = np.random.randint(1, 10, (3,4))

In [29]:
arr1

array([[9, 7, 1, 4],
       [1, 3, 8, 9],
       [6, 7, 5, 3]])

In [30]:
arr2

array([[3, 5, 1, 7],
       [3, 3, 4, 6],
       [5, 5, 2, 1]])

In [31]:
arr1+arr2

array([[12, 12,  2, 11],
       [ 4,  6, 12, 15],
       [11, 12,  7,  4]])

In [32]:
arr1*arr2

array([[27, 35,  1, 28],
       [ 3,  9, 32, 54],
       [30, 35, 10,  3]])

In [33]:
arr1/arr2

array([[3.        , 1.4       , 1.        , 0.57142857],
       [0.33333333, 1.        , 2.        , 1.5       ],
       [1.2       , 1.4       , 2.5       , 3.        ]])

In [34]:
arr1-arr2

array([[ 6,  2,  0, -3],
       [-2,  0,  4,  3],
       [ 1,  2,  3,  2]])

In [35]:
arr1 ** arr2

array([[   729,  16807,      1,  16384],
       [     1,     27,   4096, 531441],
       [  7776,  16807,     25,      3]])

In [36]:
arr1 > arr2

array([[ True,  True, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [37]:
~arr1

array([[-10,  -8,  -2,  -5],
       [ -2,  -4,  -9, -10],
       [ -7,  -8,  -6,  -4]])

#Numpy String Functions

In [38]:
arr = np.array(["bat", "cat", "rat"])
arr

array(['bat', 'cat', 'rat'], dtype='<U3')

In [39]:
np.char.upper(arr)

array(['BAT', 'CAT', 'RAT'], dtype='<U3')

In [40]:
np.char.capitalize(arr)

array(['Bat', 'Cat', 'Rat'], dtype='<U3')

In [41]:
np.char.title(arr)

array(['Bat', 'Cat', 'Rat'], dtype='<U3')

#Mathematical Funtions on Arrays

In [42]:
arr1

array([[9, 7, 1, 4],
       [1, 3, 8, 9],
       [6, 7, 5, 3]])

In [43]:
np.sin(arr1)

array([[ 0.41211849,  0.6569866 ,  0.84147098, -0.7568025 ],
       [ 0.84147098,  0.14112001,  0.98935825,  0.41211849],
       [-0.2794155 ,  0.6569866 , -0.95892427,  0.14112001]])

In [44]:
np.cos(arr1)

array([[-0.91113026,  0.75390225,  0.54030231, -0.65364362],
       [ 0.54030231, -0.9899925 , -0.14550003, -0.91113026],
       [ 0.96017029,  0.75390225,  0.28366219, -0.9899925 ]])

In [45]:
np.tan(arr1)

array([[-0.45231566,  0.87144798,  1.55740772,  1.15782128],
       [ 1.55740772, -0.14254654, -6.79971146, -0.45231566],
       [-0.29100619,  0.87144798, -3.38051501, -0.14254654]])

In [46]:
np.log10(arr1)

array([[0.95424251, 0.84509804, 0.        , 0.60205999],
       [0.        , 0.47712125, 0.90308999, 0.95424251],
       [0.77815125, 0.84509804, 0.69897   , 0.47712125]])

In [47]:
np.power(arr1, 2)

array([[81, 49,  1, 16],
       [ 1,  9, 64, 81],
       [36, 49, 25,  9]])

In [48]:
np.mean(arr1)

5.25

In [49]:
np.max(arr1)

9

In [50]:
np.std(arr1)

2.742413778650722

In [51]:
np.var(arr1)

7.520833333333333

In [52]:
np.subtract(arr1, arr2)

array([[ 6,  2,  0, -3],
       [-2,  0,  4,  3],
       [ 1,  2,  3,  2]])

In [53]:
np.multiply(arr1, arr2)

array([[27, 35,  1, 28],
       [ 3,  9, 32, 54],
       [30, 35, 10,  3]])

In [56]:
np.mod(arr1, arr2)
#returns the index wise remainder

array([[0, 2, 0, 4],
       [1, 0, 0, 3],
       [1, 2, 1, 0]])

In [55]:
np.power(arr1, arr2)

array([[   729,  16807,      1,  16384],
       [     1,     27,   4096, 531441],
       [  7776,  16807,     25,      3]])

In [58]:
np.sqrt(arr1)

array([[3.        , 2.64575131, 1.        , 2.        ],
       [1.        , 1.73205081, 2.82842712, 3.        ],
       [2.44948974, 2.64575131, 2.23606798, 1.73205081]])

In [59]:
np.exp(arr1)

array([[8.10308393e+03, 1.09663316e+03, 2.71828183e+00, 5.45981500e+01],
       [2.71828183e+00, 2.00855369e+01, 2.98095799e+03, 8.10308393e+03],
       [4.03428793e+02, 1.09663316e+03, 1.48413159e+02, 2.00855369e+01]])

#Sorting and Searching

In [61]:
arr = np.array([5,6,1,2])
arr

array([5, 6, 1, 2])

In [62]:
np.sort(arr)

array([1, 2, 5, 6])

In [64]:
np.searchsorted(arr, 3)

4

In [65]:
np.searchsorted([1,2,3,4,5], 3)

2

In [68]:
arr1 = np.array([1,2,5,7,0,0,4,0,5,0,6,0,0])
np.count_nonzero(arr1)

7

In [69]:
arr1 > 0

array([ True,  True,  True,  True, False, False,  True, False,  True,
       False,  True, False, False])

In [70]:
np.where(arr1 > 0)

(array([ 0,  1,  2,  3,  6,  8, 10]),)

In [72]:
np.extract(arr1 > 0, arr1)

array([1, 2, 5, 7, 4, 5, 6])

In [74]:
arr1 = np.array([2,0,5,4,3,0])
arr1.byteswap()

array([144115188075855872,                  0, 360287970189639680,
       288230376151711744, 216172782113783808,                  0])

#Matrix Operations

In [75]:
import numpy.matlib as nm

In [76]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [77]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [81]:
arr1 = np.random.randint(1, 10, (3,3))
arr2 = np.random.randint(1, 10, (3,3))

In [82]:
arr1

array([[3, 5, 9],
       [9, 7, 4],
       [2, 8, 8]])

In [83]:
arr2

array([[2, 1, 9],
       [8, 9, 9],
       [6, 3, 1]])

In [85]:
arr1 @ arr2
#matrix multiplication

array([[100,  75,  81],
       [ 98,  84, 148],
       [116,  98,  98]])

Solving system of linear equations

In [86]:
#   7x + 5y - 3z = 16
#   2x - 5y + 2z = -8
#   5x + 3y - 7z = 0

In [88]:
coefficients = np.array([[7,5,-3], [2,-5,2], [5,3,-7]])
coefficients

array([[ 7,  5, -3],
       [ 2, -5,  2],
       [ 5,  3, -7]])

In [91]:
constant_values = np.array([16, -8, 0])
constant_values

array([16, -8,  0])

In [92]:
np.linalg.solve(coefficients, constant_values)

array([1.11304348, 2.85217391, 2.0173913 ])

In [95]:
np.linalg.det(arr1)

274.00000000000006

In [96]:
np.linalg.inv(arr1)

array([[ 0.08759124,  0.11678832, -0.15693431],
       [-0.23357664,  0.02189781,  0.25182482],
       [ 0.21167883, -0.05109489, -0.08759124]])